name: Renew No-IP

on:
  schedule:
    - cron: '0 3 1 * *'  # Runs at 03:00 UTC on the 1st of every month
  workflow_dispatch:     # Allows manual triggering

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run renewal script
        env:
          NOIP_USERNAME: ${{ secrets.NOIP_USERNAME }}
          NOIP_PASSWORD: ${{ secrets.NOIP_PASSWORD }}
          NOIP_TOTP_KEY: ${{ secrets.NOIP_TOTP_KEY }}  # Optional
        run: |
          python noip-renew.py

