name: Renew No-IP

on:
  # run every SATURDAY at 03:00 UTC  (once per week, safely inside the 7-day window)
  schedule:
    - cron: '0 15 * * 5'
  workflow_dispatch:        # <-- leave this so you can run it by hand


jobs:
  renew:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chromium and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -s /usr/bin/chromedriver /usr/local/bin/chromedriver
          sudo ln -s /usr/bin/chromium-browser /usr/local/bin/chrome

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install undetected-chromedriver selenium pyotp deep-translator webdriver-manager

      - name: Run renewal script
        env:
          NOIP_USERNAME: ${{ secrets.NOIP_USERNAME }}
          NOIP_PASSWORD: ${{ secrets.NOIP_PASSWORD }}
          NOIP_TOTP_KEY: ${{ secrets.NOIP_TOTP_KEY }}
        run: |
          python renew.py

      - name: Upload debug artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: |
            *.png
            *.html


      - name: Upload debug screenshot (if failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-after-failure
          path: after_login.png
